import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,within,waitFor} from '@testing-library/react';
import {MemoryRouter,Route,Routes} from 'react-router-dom';
import {AppProvider,useApp} from '../context/AppContext';
import {createInitialState} from '../data/fixtures';
import type {AppState,ChatMessage} from '../domain/types';
import {appReducer} from '../domain/reducer';
import {freshGuestState} from '../world/account';
import {selectHomePresence,worldActivities,exploreActivityPair} from '../world/presenceDiscovery';
import {membershipWorldsForFan,purchaseGroupsForFan,orderState} from '../world/personalSelectors';
import {canProjectHallVoice,selectPublicVoices} from '../world/exploreDiscovery';
import {AVATAR_FITS,compatibleDigitalLook,hasAvatarFit} from '../world/avatarFit';
import {benefitDestination} from '../world/benefitDestination';
import {getPreviewCapabilities} from '../world/shopPresentation';
import {readDisplaySurfaces} from '../world/displaySurfaces';
import {FanShell} from '../components/FanShell';
import {AvatarRenderer} from '../components/AvatarRenderer';
import {WorldPlazaView} from '../views/WorldPlazaView';
import {ExploreView} from '../views/ExploreView';
import {ArtistWorldView} from '../views/ArtistWorldView';
import {FanWorldView} from '../views/FanWorldView';
import {FanShopView} from '../views/FanShopView';
import {PersonalUtilityView} from '../views/PersonalUtilityView';
import {loadState} from '../services/storageAdapter';

const initial=()=>createInitialState('vieworld-demo');
function Probe(){const{state}=useApp();return <output data-testid="presence-state">{JSON.stringify(state.fanProfile)}</output>;}
function mount(path:string,state:AppState=initial()){
 return render(<AppProvider initialState={state}><MemoryRouter initialEntries={[path]}><Routes><Route element={<FanShell/>}>
  <Route path="/" element={<WorldPlazaView/>}/><Route path="/explore" element={<ExploreView/>}/><Route path="/shop" element={<FanShopView/>}/><Route path="/me" element={<><FanWorldView/><Probe/></>}/>
  <Route path="/artist/:artistId" element={<ArtistWorldView/>}/><Route path="/artist/:artistId/hall" element={<ArtistWorldView/>}/><Route path="/artist/:artistId/archive" element={<ArtistWorldView/>}/><Route path="/artist/:artistId/moment/:momentId" element={<ArtistWorldView/>}/>
  <Route path="/memberships" element={<PersonalUtilityView/>}/><Route path="/orders" element={<PersonalUtilityView/>}/><Route path="/account/settings" element={<PersonalUtilityView/>}/><Route path="/account/help" element={<PersonalUtilityView/>}/>
 </Route></Routes></MemoryRouter></AppProvider>);
}
beforeEach(()=>{cleanup();localStorage.clear();window.matchMedia=vi.fn().mockReturnValue({matches:false,addEventListener:vi.fn(),removeEventListener:vi.fn()});});
afterEach(cleanup);

describe('Canonical presence navigation and temporal home',()=>{
 it('syncs theme changes from Settings to the shell immediately and keeps them after navigation',()=>{mount('/account/settings');fireEvent.click(screen.getByRole('button',{name:'Giao diện Đang sáng, chuyển sang tối'}));expect(screen.getByTestId('app-container')).toHaveAttribute('data-theme','dark');expect(document.documentElement.dataset.theme).toBe('dark');expect(localStorage.getItem('vieworld:appearance')).toBe('dark');fireEvent.click(screen.getByRole('link',{name:'← VieWorld'}));expect(screen.getByTestId('app-container')).toHaveAttribute('data-theme','dark');});
 it('uses a rail with no global header, hamburger, slogan or global search',()=>{const{container}=mount('/');expect(container.querySelector('.fw-header')).toBeNull();expect(screen.queryByRole('combobox')).toBeNull();expect(screen.queryByRole('button',{name:'Mở menu'})).toBeNull();const nav=screen.getByRole('navigation',{name:'Điều hướng chính'});expect(within(nav).getAllByRole('link')).toHaveLength(5);});
 it('has exactly five mobile destinations, with account instead of My Space or Bell',()=>{mount('/');const nav=screen.getByRole('navigation',{name:'Điều hướng di động'});expect(within(nav).getAllByRole('link')).toHaveLength(4);expect(within(nav).getAllByRole('button')).toHaveLength(1);expect(within(nav).queryByRole('link',{name:'My Space'})).toBeNull();});
 it('places My Space first in the account popover and opens utility main routes',()=>{mount('/');fireEvent.click(screen.getByRole('button',{name:'Tài khoản'}));const account=screen.getByRole('navigation',{name:'Tài khoản'});expect(within(account).getAllByRole('link')[0]).toHaveAttribute('href','/me');expect(within(account).getByRole('link',{name:/Hội viên & quyền lợi/})).toHaveAttribute('href','/memberships');expect(within(account).getByRole('link',{name:/Đơn hàng/})).toHaveAttribute('href','/orders');});
 it('opens and dismisses guest auth without showing an old profile menu',()=>{mount('/',freshGuestState(initial()));fireEvent.click(screen.getByRole('button',{name:'Đăng nhập'}));expect(screen.getByTestId('demo-auth-overlay')).toBeVisible();expect(screen.queryByRole('navigation',{name:'Tài khoản'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Để sau, tiếp tục khám phá'}));expect(screen.queryByRole('dialog')).toBeNull();});
 it('renders three moment windows with temporal chips instead of large headings or repeated titles',()=>{const{container}=mount('/');expect(container.querySelectorAll('.presence-home-slot')).toHaveLength(3);expect([...container.querySelectorAll('.presence-phase')].map(e=>e.textContent)).toEqual(['Vừa rồi','Đang diễn ra','Sắp tới']);expect(container.querySelectorAll('.presence-home-slot>h2.sr-only')).toHaveLength(3);expect(container.querySelector('.is-now .presence-home-tile')).not.toBeNull();for(const title of container.querySelectorAll('.presence-home-summary strong'))expect(screen.getAllByText(title.textContent!)).toHaveLength(1);expect(container.querySelector('.presence-home-timeline')?.textContent).not.toMatch(/Demo/);});
 it('keeps past, current and future separate and admits only rights-cleared sessions',()=>{const state=initial();const home=selectHomePresence(state);expect(home.recent?.phase).toBe('recent');expect(home.now?.phase).toBe('now');expect(home.next?.phase).toBe('next');expect(Date.parse(home.next!.at!)).toBeGreaterThanOrEqual(Date.parse(state.demoTime));for(const s of Object.values(state.sessions)){s.rightsApproved=false;}expect(worldActivities(state,'artist-a').some(a=>state.sessions[a.id])).toBe(false);});
 it('does not borrow the sample fan avatar or artist identity for a guest',()=>{const{container}=mount('/',freshGuestState(initial()));expect(container.querySelector('.presence-home-fan .avatar-renderer')).toBeNull();expect(screen.queryByText('Linh Nguyễn')).toBeNull();expect(within(screen.getByRole('navigation',{name:'Điều hướng chính'})).getByRole('link',{name:'Artist'})).toHaveAttribute('href','/explore?scope=following');});
 it('handles missing activities with honest empty tiles instead of fabricated counts',()=>{const state=initial();state.sessions={};state.activeTenantId='mfan-demo';const{container}=mount('/',state);expect(container.querySelectorAll('.presence-home-empty')).toHaveLength(3);expect(screen.queryByText(/đang online/i)).toBeNull();});
});
describe('Explore world bands and privacy',()=>{
 it('keeps one row per artist and no nested program row or featured section headings',()=>{const{container}=mount('/explore');expect(container.querySelectorAll('.presence-explore-row')).toHaveLength(7);expect(container.querySelector('[data-world="neon-sessions"]')).toBeNull();expect(screen.queryByRole('heading',{name:/Nổi bật/})).toBeNull();});
 it('does not project stored follow state to anonymous visitors',()=>{mount('/explore',freshGuestState(initial()));expect(screen.queryByRole('button',{name:'Đang theo dõi'})).toBeNull();expect(within(screen.getByRole('navigation',{name:'World bạn theo dõi'})).queryByRole('link',{name:'Artist A'})).toBeNull();});
 it('following shortcut scopes the same world list rather than opening another generation',()=>{const{container}=mount('/explore?scope=following');expect(container.querySelectorAll('.presence-explore-row')).toHaveLength(1);expect(container.querySelector('.presence-explore-row')).toHaveAttribute('data-world','artist-a');});
 it('promotes a matched activity while keeping the artist as result unit',()=>{const state=initial();const pair=exploreActivityPair(state,'artist-mira','Luna');expect(pair[0].title).toMatch(/Luna/);expect(pair.every(a=>a.artistId==='artist-mira')).toBe(true);});
 it('has local suggestions and hides the Your Worlds strip while searching',()=>{mount('/explore');fireEvent.change(screen.getByRole('combobox',{name:'Tìm trong Explore'}),{target:{value:'MIRA'}});expect(screen.queryByRole('navigation',{name:'World bạn theo dõi'})).toBeNull();expect(screen.getByRole('listbox')).toBeVisible();expect(screen.queryByText('Linh Nguyễn')).toBeNull();});
 it('requires global opt-in, message consent, moderation approval and known fan identity',()=>{const state=initial();const msg:ChatMessage={id:'public-check',sessionId:'hall-artist-a',fanId:state.fanProfile.id,authorName:'Fan',text:'My consented thought',timestamp:state.demoTime,explorePreviewConsent:true,explorePreviewStatus:'approved'};expect(canProjectHallVoice(state,'artist-a',msg)).toBe(false);state.fanProfile.sharing={hallPublicProjectionEnabled:true,communityPresenceEnabled:false};expect(canProjectHallVoice(state,'artist-a',msg)).toBe(true);expect(canProjectHallVoice(state,'artist-a',{...msg,fanId:'unknown'})).toBe(false);expect(canProjectHallVoice(state,'artist-a',{...msg,isReported:true})).toBe(false);});
 it('withdrawing consent unpublishes a message without deleting it',()=>{let state=initial();state.fanProfile.sharing={hallPublicProjectionEnabled:true,communityPresenceEnabled:false};state.hallMessages={'artist-a':[{id:'share',sessionId:'hall-artist-a',fanId:state.fanProfile.id,authorName:'Fan',text:'Private now',timestamp:state.demoTime,explorePreviewConsent:true,explorePreviewStatus:'approved'}]};state=appReducer(state,{type:'SET_HALL_PUBLIC_CONSENT',worldId:'artist-a',messageId:'share',consent:false});expect(selectPublicVoices(state,'artist-a').some(v=>v.id==='share')).toBe(false);expect(state.hallMessages!['artist-a']).toHaveLength(1);});
});
describe('Artist hierarchy and membership destinations',()=>{
 it('uses one primary activity and one secondary activity, not equal banner cards',()=>{const{container}=mount('/artist/artist-a');expect(container.querySelectorAll('.presence-artist-main>.artist-world-object')).toHaveLength(1);expect(container.querySelectorAll('.presence-artist-side>.artist-world-object')).toHaveLength(1);expect(container.querySelector('.presence-artist-voices')).not.toBeNull();});
 it('follow from a guest asks for demo login instead of mutating the sample fan',()=>{const state=freshGuestState(initial());state.followedWorldIds=[];mount('/artist/artist-a',state);fireEvent.click(screen.getByRole('button',{name:'Theo dõi'}));expect(screen.getByTestId('demo-auth-overlay')).toBeVisible();expect(loadState().state.followedWorldIds).toEqual([]);});
 it('opens public Hall for nonmembers but requires membership for Lounge',()=>{const state=initial();state.memberships={};mount('/artist/artist-a/hall',state);expect(screen.getByRole('log',{name:'Tin nhắn trong Hall'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:/Member Lounge/}));expect(screen.queryByRole('log')).toBeNull();expect(screen.getByRole('link',{name:'Xem hội viên'})).toHaveAttribute('href','/memberships?artist=artist-a');});
 it('keeps replies in a thread inspector and removes them from the main conversation',()=>{const state=initial();state.hallMessages={'artist-a':[{id:'root',sessionId:'hall-artist-a',fanId:state.fanProfile.id,authorName:'Fan',text:'Root thought',timestamp:state.demoTime},{id:'reply',sessionId:'hall-artist-a',fanId:state.fanProfile.id,authorName:'Fan',text:'Thread thought',timestamp:state.demoTime,replyToId:'root'}]};mount('/artist/artist-a/hall?room=hall-artist-a',state);expect(within(screen.getByRole('log')).queryByText('Thread thought')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'1 trả lời'}));expect(screen.getByText('Thread thought')).toBeVisible();});
 it('archive is public with four filters and About, never private capsules',()=>{mount('/artist/artist-a/archive');expect(screen.getByRole('heading',{name:'Kho lưu trữ'})).toBeVisible();expect(screen.getByRole('heading',{name:'Về Artist A'})).toBeVisible();expect(screen.queryByRole('button',{name:'Capsule'})).toBeNull();expect(screen.queryByRole('heading',{name:'Mới được lưu'})).toBeNull();});
 it('deduplicates membership worlds and prefers active records without inventing tenure',()=>{const state=initial();const member=Object.values(state.memberships)[0];state.memberships.duplicate={...member,id:'duplicate',status:'inactive',updatedAt:'2099-01-01T00:00:00Z'};const worlds=membershipWorldsForFan(state);expect(worlds.filter(w=>w.world.id===member.worldId)).toHaveLength(1);expect(worlds.find(w=>w.world.id===member.worldId)?.active).toBe(true);delete member.startedAt;expect(membershipWorldsForFan(state).find(w=>w.world.id===member.worldId)?.months).toBe(-1);});
 it('gives no invented benefit destination or expiry when metadata is absent',()=>{const state=initial();const b=Object.values(state.benefits)[0];expect(benefitDestination(state,b)).toBeUndefined();expect(b.availableFrom).toBeUndefined();});
 it('validates supplied benefit destinations and time windows',()=>{const state=initial();const base=Object.values(state.benefits)[0];const b={...base,status:'eligible' as const,target:{type:'artist_hall' as const,worldId:'artist-a'}};expect(benefitDestination(state,b)).toBe('/artist/artist-a/hall?room=member-lounge-artist-a');expect(benefitDestination(state,{...b,expiresAt:'2020-01-01T00:00:00Z'})).toBeUndefined();expect(appReducer({...state,benefits:{[b.id]:{...b,availableFrom:'2099-01-01T00:00:00Z'}}},{type:'CLAIM_BENEFIT',benefitId:b.id}).lastError?.code).toBe('BENEFIT_WINDOW_CLOSED');});
 it('groups order lines by checkout instead of counting each line as an order',()=>{const state=initial();const product=state.products['product-cap-real'];const line={id:'one',tenantId:state.activeTenantId,version:1,updatedAt:state.demoTime,fanId:state.fanProfile.id,productId:product.id,worldId:'artist-a',sourceRef:'test',requestId:'test',status:'paid' as const,checkoutId:'checkout',quantity:1};state.orders={one:line,two:{...line,id:'two',quantity:2}};expect(purchaseGroupsForFan(state)).toHaveLength(1);expect(purchaseGroupsForFan(state)[0].count).toBe(3);expect(orderState(line,state)).toBe('Đang chuẩn bị hàng');});
});
describe('Room, fitted avatar and family detail',()=>{
 it('opens My Space room-first with no legacy management tabs',()=>{const{container}=mount('/me');expect(container.querySelector('.v6-room-art')).toHaveAttribute('src','/images/myspace-room-v2.png');expect(screen.queryByRole('button',{name:'Phòng trưng bày'})).toBeNull();expect(screen.getByRole('button',{name:'Đổi diện mạo avatar'})).toBeEnabled();});
 it('opens appearance from the avatar and room display from the rack',()=>{mount('/me');fireEvent.click(screen.getByRole('button',{name:'Đổi diện mạo avatar'}));expect(screen.getByRole('dialog',{name:'Avatar của bạn'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Đóng'}));fireEvent.click(screen.getByRole('button',{name:/Giá trang phục: chưa trưng bày/}));expect(screen.getByRole('dialog',{name:'Trưng bày Giá trang phục'})).toBeVisible();expect(screen.queryByRole('button',{name:'Trang phục'})).toBeNull();});
 it('opens guestbook context and legacy collection links without losing the room',()=>{const{container}=mount('/me?panel=capsules');expect(screen.getByRole('button',{name:'Kỷ niệm & dấu mốc'})).toHaveAttribute('aria-pressed','true');expect(container.querySelector('.v6-room-art')).not.toBeNull();});
 it('keeps typed collection deep links connected',()=>{mount('/me?section=collection&type=ticket');expect(screen.getByRole('combobox',{name:'Tìm trong bộ sưu tập'})).toBeVisible();expect(screen.getByRole('button',{name:'Vé'})).toHaveAttribute('aria-pressed','true');});
 it('projects selected owned items as a ghost in the actual room and saves only on confirmation',()=>{const state=initial();const p=state.products['product-lightstick-digital'];state.orders={owned:{id:'owned',tenantId:state.activeTenantId,version:1,updatedAt:state.demoTime,fanId:state.fanProfile.id,productId:p.id,worldId:'artist-a',sourceRef:'test',requestId:'test',status:'fulfilled'}};const{container}=mount(`/me?place=${p.id}&surface=lightstick`,state);expect(container.querySelector(`[data-room-item="${p.id}"]`)).toHaveClass('is-ghost');expect(readDisplaySurfaces(loadState().state.fanProfile).lightstick.itemIds).toEqual([]);fireEvent.click(screen.getByRole('button',{name:'Lưu thay đổi'}));expect(readDisplaySurfaces(loadState().state.fanProfile).lightstick.itemIds).toEqual([p.id]);expect(container.querySelector(`[data-room-item="${p.id}"]`)).not.toHaveClass('is-ghost');});
 it('closing a ghost preview does not grant, place or remove ownership',()=>{const state=initial();const p=state.products['product-lightstick-digital'];state.orders={owned:{id:'owned',tenantId:state.activeTenantId,version:1,updatedAt:state.demoTime,fanId:state.fanProfile.id,productId:p.id,worldId:'artist-a',sourceRef:'test',requestId:'test',status:'fulfilled'}};mount(`/me?place=${p.id}&surface=lightstick`,state);fireEvent.click(screen.getByRole('button',{name:'Đóng'}));expect(readDisplaySurfaces(loadState().state.fanProfile).lightstick.itemIds).toEqual([]);expect(loadState().state.orders.owned.status).toBe('fulfilled');});
 it('uses one canonical body for all appearances and only authored item fits',()=>{for(const appearance of ['original','wave','bob','curl'] as const){const{container,unmount}=render(<AvatarRenderer appearance={appearance} digitalLook={{shirt:'star-shirt',hat:'star-cap',lightstick:'mira-lightstick'}}/>);expect(container.querySelector('.vw-equipped-fan')).toHaveAttribute('data-rig','canonical');expect(new Set([...container.querySelectorAll('[data-visual-id]')].map(el=>el.getAttribute('data-visual-id'))).size).toBe(3);unmount();}expect(hasAvatarFit('headband')).toBe(false);expect(compatibleDigitalLook({hat:'unknown',shirt:'star-light'})).toEqual({});});
 it('preserves authored item identity in avatar fallback and omits old floating preset accessories',()=>{const{container}=render(<AvatarRenderer accessoryId="earpiece_glow" digitalLook={{shirt:'star-shirt'}}/>);expect(screen.queryByTestId('preview-accessory-earpiece')).toBeNull();fireEvent.error(container.querySelector('image')!);expect(container.querySelector('[data-visual-id="star-shirt"]')).not.toBeNull();});
 it('never grants preview to an unsupported wearable even if metadata claims it',()=>{const state=initial();const p={...state.products['product-cap-digital'],digitalItemId:'unfitted',previewCapabilities:{avatar:true,room:false}};expect(getPreviewCapabilities(p,[p])).toEqual({avatar:false,room:false});expect(Object.keys(AVATAR_FITS)).toHaveLength(8);});
 it('opens product-family detail in the centered layout with explicit edition choice',()=>{mount('/shop?product=product-star-shirt-real');const panel=screen.getByRole('dialog');expect(panel).toHaveClass('fw-panel-product');const selector=panel.querySelector('.fw-variant-selector')!;expect(within(selector as HTMLElement).getByRole('button',{name:/Ngoài đời/})).toHaveAttribute('aria-pressed','true');expect(within(selector as HTMLElement).getByRole('button',{name:/Trong VieWorld/})).toBeVisible();});
 it('has contextual try-on without fake pose controls or implicit purchase',()=>{const state=freshGuestState(initial());mount('/shop?product=product-star-shirt-real',state);fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Thử mặc'}));const panel=screen.getByRole('dialog');expect(panel.querySelector('[data-visual-id="star-shirt"]')).not.toBeNull();expect(screen.queryByRole('button',{name:'Vẫy lightstick'})).toBeNull();expect(screen.queryByText('Linh Nguyễn')).toBeNull();expect(loadState().state.orders).toEqual({});});
 it('already owned digital editions acknowledge ownership instead of duplicate purchase',()=>{const state=initial();state.orders={owned:{id:'owned',tenantId:state.activeTenantId,version:1,updatedAt:state.demoTime,fanId:state.fanProfile.id,productId:'product-cap-digital',worldId:'artist-a',sourceRef:'test',requestId:'test',status:'fulfilled'}};mount('/shop?product=product-cap-digital',state);expect(screen.getByText(/Bạn đã có phiên bản này/)).toBeVisible();expect(within(screen.getByRole('dialog')).queryByRole('button',{name:'Thêm vào giỏ'})).toBeNull();});
 it('keeps membership as a join/view path, never a cart purchase',()=>{mount('/shop?product=product-member-preview');const panel=screen.getByRole('dialog');expect(within(panel).queryByRole('button',{name:'Thêm vào giỏ'})).toBeNull();expect(within(panel).getByRole('link',{name:'Xem hội viên của bạn'})).toHaveAttribute('href','/memberships?artist=artist-a');});
 it('help for a guest does not expose stored private support cases or orders',()=>{const state=freshGuestState(initial());state.supportCases.private={id:'private',tenantId:state.activeTenantId,version:1,updatedAt:state.demoTime,fanId:state.fanProfile.id,subjectType:'benefit',subjectId:'benefit-early-access-01',status:'open',nextAction:'check'};mount('/account/help',state);expect(screen.queryByRole('link',{name:'Hồ sơ private'})).toBeNull();expect(screen.getByRole('combobox',{name:'Nội dung cần hỗ trợ'}).querySelectorAll('option')).toHaveLength(1);});
 it('nested collection detail closes with Escape while keeping the collection open',async()=>{const state=initial();state.orders={owned:{id:'owned',tenantId:state.activeTenantId,version:1,updatedAt:state.demoTime,fanId:state.fanProfile.id,productId:'product-cap-digital',worldId:'artist-a',sourceRef:'test',requestId:'test',status:'fulfilled'}};mount('/me?section=collection',state);fireEvent.click(screen.getByRole('button',{name:'Tùy chọn Nón Everyday Star · Digital'}));fireEvent.click(screen.getByRole('menuitem',{name:'Xem chi tiết'}));expect(screen.getAllByRole('dialog')).toHaveLength(2);fireEvent.keyDown(window,{key:'Escape'});await waitFor(()=>expect(screen.getAllByRole('dialog')).toHaveLength(1));});
});
