import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { AppProvider } from '../context/AppContext';
import { ArtistGalleryView } from '../views/ArtistGalleryView';
import { FanWorldView } from '../views/FanWorldView';
import { WorldPlazaView } from '../views/WorldPlazaView';
import { AvatarRenderer } from '../components/AvatarRenderer';
import { createInitialState } from '../data/fixtures';
import { saveState, loadState } from '../services/storageAdapter';
import { panelRoute, PANEL_HOME } from '../world/places';
function mount(path:string){return render(<AppProvider><MemoryRouter initialEntries={[path]}><Routes><Route path="/" element={<WorldPlazaView/>}/><Route path="/artists" element={<ArtistGalleryView/>}/><Route path="/moments" element={<FanWorldView/>}/><Route path="/archive" element={<FanWorldView/>}/><Route path="/worlds/:worldId" element={<FanWorldView/>}/><Route path="/me" element={<FanWorldView/>}/></Routes></MemoryRouter></AppProvider>);}
describe('World v4 consistency',()=>{
 beforeEach(()=>localStorage.clear());
 it('does not scope the plaza or private room to the last visited artist',()=>{const state=createInitialState('vieworld-demo');state.fanProfile.worldJourney={...state.fanProfile.worldJourney!,lastWorldId:'neon-sessions',readNoteIds:[]};saveState(state);const v=mount('/');expect(screen.queryByRole('combobox')).not.toBeInTheDocument();expect(within(screen.getByRole('navigation',{name:'Các nơi của VieWorld'})).getByRole('link',{name:/Artist Home/})).toHaveAttribute('href','/artists');v.unmount();mount('/me');expect(screen.queryByText('Neon Sessions')).not.toBeInTheDocument();expect(screen.queryByTestId('avatar-renderer-artist')).not.toBeInTheDocument();});
 it('showcases artists and IP separately, with search and persisted follows',()=>{mount('/artists');fireEvent.change(screen.getByRole('textbox',{name:'Tìm artist hoặc chương trình'}),{target:{value:'neon'}});expect(screen.queryByRole('link',{name:'Ghé Artist A'})).not.toBeInTheDocument();expect(screen.getByRole('link',{name:'Ghé Neon Sessions'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Theo dõi Neon Sessions'}));expect(loadState('vieworld-demo','fan-linh').state.followedWorldIds).toContain('neon-sessions');});
 it('has an honest empty discovery state',()=>{mount('/artists');fireEvent.change(screen.getByRole('textbox',{name:'Tìm artist hoặc chương trình'}),{target:{value:'does not exist'}});expect(screen.getByText('Chưa tìm thấy tên này.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Xem tất cả'}));expect(screen.getByRole('link',{name:'Ghé Artist A'})).toBeInTheDocument();});
 it('v6 keeps discovery free of live/community controls',()=>{mount('/artists');expect(screen.getByRole('link',{name:'Ghé Artist A'})).toHaveAttribute('href','/moments?artist=artist-a');expect(screen.queryByRole('button',{name:'Live & Concert'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Hall hội viên'})).not.toBeInTheDocument();});
 it('v6 opens one artist community without pretending live presence',()=>{mount('/moments');expect(screen.getByRole('combobox',{name:'Chọn nhà nghệ sĩ'})).toHaveValue('artist-a');expect(screen.queryByTestId('avatar-renderer-artist')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Hall hội viên'}));expect(screen.getByText(/Giao lưu và ghé My Space/)).toBeInTheDocument();});
 it('only edits shelf placement in My Space and links to Archive for collection management',()=>{mount('/me?panel=showcase');const panel=screen.getByRole('dialog');expect(within(panel).queryByRole('textbox')).not.toBeInTheDocument();expect(within(panel).getByRole('link',{name:'Mở bộ sưu tập riêng →'})).toHaveAttribute('href','/me?section=collection&panel=capsules');expect(within(panel).getByRole('button',{name:'Ô 1'})).toHaveAttribute('aria-pressed','true');});
 it('maps cross-place actions to one feature owner',()=>{expect(PANEL_HOME.wardrobe).toBe('myspace');expect(panelRoute('capsules','neon-sessions')).toBe('/me?panel=capsules&section=collection');expect(panelRoute('concerts','artist-a')).toBe('/moments?panel=concerts&artist=artist-a');expect(panelRoute('news','artist-a')).toBe('/moments?panel=news&artist=artist-a');});
 it('loads cute character art and preserves deterministic fallback if art fails',()=>{const {container}=render(<AvatarRenderer role="fan" size="lg" accessoryId="earpiece_glow"/>);const img=container.querySelector('img')!;expect(img).toHaveAttribute('src','/images/characters-v4/fan.webp');expect(screen.getByTestId('preview-accessory-earpiece')).toBeInTheDocument();fireEvent.error(img);expect(container.querySelector('img')).toBeNull();expect(screen.getByTestId('preview-accessory-earpiece')).toBeInTheDocument();});
});
