import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import { AppProvider } from '../context/AppContext';
import { appReducer } from '../domain/reducer';
import { createInitialState } from '../data/fixtures';
import { cartFingerprint, cartProblem, orderAmount } from '../world/commerce';
import { historyCards, returnedCount } from '../world/history';
import { currentPublicFan } from '../world/community';
import { ownsDigitalProduct } from '../world/merchCatalog';
import { saveState, loadState } from '../services/storageAdapter';
import { FanShell } from '../components/FanShell';
import { CartView } from '../views/CartView';
import { FanShopView } from '../views/FanShopView';
import { MemberSpaceView } from '../views/MemberSpaceView';
import { ArchiveCollection } from '../components/ArchiveCollection';
const initial=()=>createInitialState('vieworld-demo');
function basket(){let s=appReducer(initial(),{type:'ADD_TO_CART',productId:'product-star-shirt-real',optionLabel:'M'});return appReducer(s,{type:'ADD_TO_CART',productId:'product-cap-digital'});}
function checked(){const s=basket();return appReducer(s,{type:'CHECKOUT_CART',requestId:'check-1',fingerprint:cartFingerprint(s)});}
describe('World v5 journeys',()=>{
 beforeEach(()=>localStorage.clear());
 it('adding and editing a cart creates no orders or rights',()=>{let s=basket();expect(s.cart).toHaveLength(2);expect(Object.keys(s.orders)).toHaveLength(0);expect(ownsDigitalProduct(s,s.products['product-cap-digital'])).toBe(false);s=appReducer(s,{type:'SET_CART_QUANTITY',key:s.cart![0].key,quantity:3});expect(s.cart![0].quantity).toBe(3);});
 it('requires sizes and blocks previews, stock, foreign benefits and invalid quantities',()=>{let s=initial();expect(appReducer(s,{type:'ADD_TO_CART',productId:'product-star-shirt-real'}).lastError).toBeDefined();expect(appReducer(s,{type:'ADD_TO_CART',productId:'product-ticket-preview'}).lastError).toBeDefined();s=basket();expect(appReducer(s,{type:'SET_CART_QUANTITY',key:s.cart![0].key,quantity:NaN}).cart).toEqual(s.cart);s.products['product-star-shirt-real'].stockCount=0;expect(cartProblem(s)).toContain('tồn kho');expect(appReducer(s,{type:'SET_CART_QUANTITY',key:s.cart![0].key,quantity:0}).cart).toHaveLength(1);});
 it('one digital edition per cart while physical quantities aggregate across sizes',()=>{let s=basket();s=appReducer(s,{type:'ADD_TO_CART',productId:'product-cap-digital'});expect(s.cart!.find(l=>l.productId==='product-cap-digital')!.quantity).toBe(1);s.products['product-star-shirt-real'].stockCount=1;const next=appReducer(s,{type:'ADD_TO_CART',productId:'product-star-shirt-real',optionLabel:'L'});expect(next.cart).toEqual(s.cart);expect(next.lastError).toBeDefined();});
 it('checkout validates atomically and rejects stale review totals',()=>{const s=basket();const fingerprint=cartFingerprint(s);s.products['product-cap-digital'].priceVND+=100;const failed=appReducer(s,{type:'CHECKOUT_CART',requestId:'stale',fingerprint});expect(Object.keys(failed.orders)).toHaveLength(0);expect(failed.cart).toHaveLength(2);});
 it('checkout retry is idempotent after emptying the cart, snapshots survive price changes',()=>{const s=checked();expect(s.cart).toEqual([]);expect(Object.keys(s.orders)).toHaveLength(2);expect(appReducer(s,{type:'CHECKOUT_CART',requestId:'check-1',fingerprint:'old'})).toBe(s);const order=Object.values(s.orders)[0];const amount=orderAmount(order,s);s.products[order.productId].priceVND=1;expect(orderAmount(order,s)).toBe(amount);});
 it('group payment is atomic, deducts stock once and never fulfils',()=>{let s=checked();s=appReducer(s,{type:'PAY_CHECKOUT',checkoutId:'check-1'});expect(Object.values(s.orders).every(o=>o.status==='paid')).toBe(true);expect(s.products['product-cap-digital'].stockCount).toBe(29);expect(appReducer(s,{type:'PAY_CHECKOUT',checkoutId:'check-1'})).toBe(s);expect(ownsDigitalProduct(s,s.products['product-cap-digital'])).toBe(false);const o=Object.values(s.orders).find(o=>o.productId==='product-cap-digital')!;s=appReducer(s,{type:'SIMULATE_FULFILMENT',orderId:o.id});expect(ownsDigitalProduct(s,s.products[o.productId])).toBe(true);});
 it('insufficient stock at payment changes no receipts or inventory',()=>{const s=checked();s.products['product-cap-digital'].stockCount=0;const next=appReducer(s,{type:'PAY_CHECKOUT',checkoutId:'check-1'});expect(next.orders).toEqual(s.orders);expect(next.products).toEqual(s.products);expect(next.lastError).toBeDefined();});
 it('cancelled checkout cannot pay and does not consume inventory',()=>{const s=appReducer(checked(),{type:'CANCEL_CHECKOUT',checkoutId:'check-1'});expect(Object.values(s.orders).every(o=>o.status==='cancelled')).toBe(true);expect(appReducer(s,{type:'PAY_CHECKOUT',checkoutId:'check-1'}).orders).toEqual(s.orders);expect(s.products['product-cap-digital'].stockCount).toBe(30);});
 it('group receipts reject a mismatched legacy request and other fans',()=>{const s=checked();const o=Object.values(s.orders)[0];expect(appReducer(s,{type:'SIMULATE_PAYMENT',orderId:o.id,requestId:'wrong'}).lastError?.code).toBe('INVALID_REQUEST_ID');const foreign={...s,fanProfile:{...s.fanProfile,id:'different'}};expect(appReducer(foreign,{type:'PAY_CHECKOUT',checkoutId:'check-1'}).orders).toEqual(s.orders);});
 it('storage roundtrip preserves cart, old orders and optional fields',()=>{let s=basket();s=appReducer(s,{type:'CREATE_ORDER',productId:'product-pin-01',requestId:'legacy'});saveState(s);const next=loadState(s.activeTenantId,s.fanProfile.id).state;expect(next.cart).toEqual(s.cart);expect(next.orders).toEqual(s.orders);});
 it('sample cards are explicit and idempotent, never create attendance or access',()=>{const s=initial();expect(historyCards(s)).toEqual([]);const next=appReducer(s,{type:'IMPORT_DEMO_CARDS'});expect(historyCards(next)).toHaveLength(20);expect(appReducer(next,{type:'IMPORT_DEMO_CARDS'}).ticketArchive).toHaveLength(20);expect(next.participations).toEqual(s.participations);expect(next.memberships).toEqual(s.memberships);});
 it('10/20 returns preserve exact IDs and reject reuse, duplicates, and foreign cards',()=>{let s=appReducer(initial(),{type:'IMPORT_DEMO_CARDS'});const ids=historyCards(s).map(c=>c.id);expect(appReducer(s,{type:'RETURN_HISTORY_CARDS',cardIds:Array(10).fill(ids[0])}).lastError).toBeDefined();s=appReducer(s,{type:'RETURN_HISTORY_CARDS',cardIds:ids.slice(0,10)});expect(returnedCount(s)).toBe(10);expect(historyCards(s).map(c=>c.id)).toEqual(ids);expect(appReducer(s,{type:'RETURN_HISTORY_CARDS',cardIds:ids.slice(0,10)}).lastError).toBeDefined();s=appReducer(s,{type:'RETURN_HISTORY_CARDS',cardIds:ids.slice(10)});expect(returnedCount(s)).toBe(20);saveState(s);expect(returnedCount(loadState(s.activeTenantId,s.fanProfile.id).state)).toBe(20);});
 it('public identity can only wear earned badges and does not expose private state',()=>{let s=initial();expect(appReducer(s,{type:'SAVE_PUBLIC_IDENTITY',bio:'Hello',mood:'Acoustic',badge:20}).lastError).toBeDefined();s=appReducer(s,{type:'SAVE_PUBLIC_IDENTITY',bio:'Hello',mood:'Acoustic'});const projected=currentPublicFan(s);expect(projected.bio).toBe('Hello');expect(projected).not.toHaveProperty('orders');expect(projected).not.toHaveProperty('ticketArchive');expect(projected).not.toHaveProperty('privateNote');});
 it('four primary destinations, collection belongs to My Space',()=>{render(<AppProvider><MemoryRouter initialEntries={['/archive']}><Routes><Route path="*" element={<FanShell/>}/></Routes></MemoryRouter></AppProvider>);const nav=screen.getByRole('navigation',{name:'Điều hướng chính'});expect(within(nav).getAllByRole('link')).toHaveLength(4);expect(within(nav).getByRole('link',{name:'My Space'})).toHaveAttribute('aria-current','page');expect(screen.getByRole('link',{name:'VieWorld — về thế giới'})).toHaveAttribute('href','/');});
 it('fan can add product, review and create pending grouped checkout without payment',()=>{render(<AppProvider><MemoryRouter initialEntries={['/shop?product=product-cap-digital']}><Routes><Route path="/shop" element={<FanShopView/>}/><Route path="/cart" element={<CartView/>}/><Route path="/checkout/:checkoutId" element={<CartView/>}/></Routes></MemoryRouter></AppProvider>);fireEvent.click(screen.getByRole('button',{name:'Thêm vào giỏ đồ'}));expect(Object.keys(loadState('vieworld-demo','fan-linh').state.orders)).toHaveLength(0);fireEvent.click(screen.getByRole('link',{name:'Xem giỏ & chốt đơn →'}));fireEvent.click(screen.getByRole('button',{name:'Kiểm tra đơn →'}));const confirm=screen.getByRole('button',{name:'Chốt đơn · sang thanh toán'});expect(confirm).toBeDisabled();fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(confirm);expect(screen.getByRole('heading',{name:/^Thanh toán mô phỏng/})).toBeInTheDocument();expect(Object.values(loadState('vieworld-demo','fan-linh').state.orders)[0].status).toBe('pending');});
 it('visitor sees demo fan and item details but never edit or private fields',()=>{render(<AppProvider><MemoryRouter initialEntries={['/members/fan-mai']}><Routes><Route path="/members/:fanId" element={<MemberSpaceView/>}/></Routes></MemoryRouter></AppProvider>);expect(screen.getByRole('heading',{name:/Ghé nhà Mai Anh/})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Đĩa đang nghe: First Notes · CD Album'}));expect(screen.getByText(/Album được Mai chọn/)).toBeInTheDocument();expect(screen.queryByRole('textbox')).not.toBeInTheDocument();expect(screen.queryByText('Trang trí phòng')).not.toBeInTheDocument();});
 it('archive requires an explicit fixture action and confirmation before return',()=>{render(<AppProvider><MemoryRouter><ArchiveCollection/></MemoryRouter></AppProvider>);fireEvent.click(screen.getByRole('button',{name:'Thêm bộ 20 thẻ mẫu'}));fireEvent.click(screen.getByRole('button',{name:'Chọn 10 thẻ còn giữ'}));expect(returnedCount(loadState('vieworld-demo','fan-linh').state)).toBe(0);fireEvent.click(screen.getByRole('button',{name:'Kiểm tra lựa chọn'}));fireEvent.click(screen.getByRole('button',{name:'Xác nhận trả thẻ demo'}));expect(returnedCount(loadState('vieworld-demo','fan-linh').state)).toBe(10);expect(historyCards(loadState('vieworld-demo','fan-linh').state)).toHaveLength(20);});
});
