import { beforeEach, describe, expect, it } from 'vitest';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { AppProvider } from '../context/AppContext';
import { ArtistGalleryView } from '../views/ArtistGalleryView';
import { FanWorldView } from '../views/FanWorldView';
import { WorldPlazaView } from '../views/WorldPlazaView';
import { AvatarRenderer } from '../components/AvatarRenderer';
import { createInitialState } from '../data/fixtures';
import { saveState } from '../services/storageAdapter';
import { panelRoute, PANEL_HOME } from '../world/places';
function mount(path:string){return render(<AppProvider><MemoryRouter initialEntries={[path]}><Routes><Route path="/" element={<WorldPlazaView/>}/><Route path="/artists" element={<ArtistGalleryView/>}/><Route path="/moments" element={<FanWorldView/>}/><Route path="/archive" element={<FanWorldView/>}/><Route path="/worlds/:worldId" element={<FanWorldView/>}/><Route path="/me" element={<FanWorldView/>}/></Routes></MemoryRouter></AppProvider>);}
describe('World v4 consistency',()=>{
 beforeEach(()=>localStorage.clear());
 it('keeps home and private room global while allowing a contextual return',()=>{const state=createInitialState('vieworld-demo');state.fanProfile.worldJourney={...state.fanProfile.worldJourney!,lastWorldId:'neon-sessions',readNoteIds:[]};saveState(state);const v=mount('/');expect(screen.queryByRole('combobox')).not.toBeInTheDocument();expect(screen.getByRole('link',{name:/Trở lại với Neon Sessions/})).toHaveAttribute('href','/explore');v.unmount();mount('/me');expect(screen.queryByText('Neon Sessions')).not.toBeInTheDocument();expect(screen.queryByTestId('avatar-renderer-artist')).not.toBeInTheDocument();});
 it('treats Neon Sessions as a program, not a standalone Artist World',()=>{const {container}=mount('/artists?q=neon');expect(container.querySelector('[data-world="neon-sessions"]')).toBeNull();expect(screen.queryByRole('link',{name:'Vào world của Neon Sessions'})).not.toBeInTheDocument();});
 it('has an honest empty discovery state',()=>{mount('/artists?q=does%20not%20exist');expect(screen.getByText(/Chưa tìm thấy Artist World phù hợp/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Xóa tìm kiếm'}));expect(screen.getByRole('link',{name:'Vào world của Artist A'})).toBeInTheDocument();});
 it('keeps discovery separate from artist community controls',()=>{mount('/artists');expect(screen.getByRole('link',{name:'Vào world của Artist A'})).toHaveAttribute('href','/artist/artist-a');expect(screen.queryByRole('button',{name:'Live & Concert'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Hall hội viên'})).not.toBeInTheDocument();});
 it('v6 opens one artist community without pretending live presence',()=>{mount('/moments');expect(screen.getByRole('combobox',{name:'Chọn nhà nghệ sĩ'})).toHaveValue('artist-a');expect(screen.queryByTestId('avatar-renderer-artist')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Hall hội viên'}));expect(screen.getByText(/Giao lưu và ghé My Space/)).toBeInTheDocument();});
 it('only edits shelf placement in My Space and links to Archive for collection management',()=>{mount('/me?panel=showcase');const panel=screen.getByRole('dialog');expect(within(panel).queryByRole('textbox')).not.toBeInTheDocument();expect(within(panel).getByRole('link',{name:'Mở bộ sưu tập riêng →'})).toHaveAttribute('href','/me?section=collection&panel=capsules');expect(within(panel).getByRole('button',{name:'Ô 1'})).toHaveAttribute('aria-pressed','true');});
 it('maps cross-place actions to one feature owner',()=>{expect(PANEL_HOME.wardrobe).toBe('myspace');expect(panelRoute('capsules','neon-sessions')).toBe('/me?panel=capsules&section=collection');expect(panelRoute('concerts','artist-a')).toBe('/artist/artist-a');expect(panelRoute('news','artist-a')).toBe('/artist/artist-a');expect(panelRoute('hall','artist-a')).toBe('/artist/artist-a/hall');});
 it('loads cute character art and preserves deterministic fallback if art fails',()=>{const {container}=render(<AvatarRenderer role="fan" size="lg" accessoryId="earpiece_glow"/>);const img=container.querySelector('img')!;expect(img).toHaveAttribute('src','/images/characters-v4/fan.webp');expect(screen.getByTestId('preview-accessory-earpiece')).toBeInTheDocument();fireEvent.error(img);expect(container.querySelector('img')).toBeNull();expect(screen.getByTestId('preview-accessory-earpiece')).toBeInTheDocument();});
 it('uses optimized artist artwork for every artist identity',()=>{const {container,rerender}=render(<AvatarRenderer role="artist" artistId="artist-a"/>);expect(container.querySelector('img')).toHaveAttribute('src','/images/characters-v4/avatar-artist-a.webp');rerender(<AvatarRenderer role="artist" artistId="artist-mira"/>);expect(container.querySelector('img')).toHaveAttribute('src','/images/characters-v4/avatar-artist-mira.webp');rerender(<AvatarRenderer role="artist" artistId="artist-kai"/>);expect(container.querySelector('img')).toHaveAttribute('src','/images/characters-v4/avatar-artist-kai.webp');rerender(<AvatarRenderer role="artist" artistId="neon-sessions"/>);expect(container.querySelector('img')).toHaveAttribute('src','/images/characters-v4/avatar-neon-sessions.webp');});
});
