import { AppState, Product } from '../domain/types';

export const MERCH_IMAGE_ROOT = '/images/merch-v2';
export const DELIVERY_LABELS = { physical: 'Hàng thật', digital: 'Digital', bundle: 'Hàng thật + Digital' };
const base = { tenantId: 'vieworld-demo' as const, worldId: 'artist-a', version: 1, updatedAt: '2026-09-11T05:00:00Z', isAvailable: true, stockCount: 30 };
export const NEW_MERCH: Record<string, Product> = Object.fromEntries([
  { id: 'product-star-shirt-real', familyId: 'star-shirt', title: 'Áo Star Club', priceVND: 390000, category: 'merch', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 10/2026', batchLabel: 'Đợt 1', image: 'shirt-physical', digitalImage: 'shirt-digital', description: 'Áo cotton màu kem, cổ olive và ngôi sao thêu nhỏ. Bản mẫu thiết kế, không phải ảnh hàng đã sản xuất.', sizes: ['S', 'M', 'L', 'XL'], includes: ['1 áo cotton ngoài đời', 'Không kèm trang phục avatar'] },
  { id: 'product-star-shirt-digital', familyId: 'star-shirt', title: 'Áo Star Club · Digital', priceVND: 45000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'shirt-digital', digitalImage: 'shirt-digital', digitalSlot: 'shirt', digitalItemId: 'star-shirt', includes: ['1 trang phục cho avatar VieWorld', 'Không giao áo ngoài đời'] },
  { id: 'product-star-shirt-bundle', familyId: 'star-shirt', title: 'Áo Star Club · Duo', priceVND: 420000, category: 'merch', delivery: 'bundle', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 10/2026', batchLabel: 'Đợt 1', image: 'shirt-physical', digitalImage: 'shirt-digital', digitalSlot: 'shirt', digitalItemId: 'star-shirt', sizes: ['S', 'M', 'L', 'XL'], includes: ['1 áo cotton ngoài đời', '1 trang phục avatar sau bàn giao mô phỏng'] },
  { id: 'product-cap-real', familyId: 'star-cap', title: 'Nón Everyday Star', priceVND: 250000, category: 'merch', delivery: 'physical', releaseType: 'in_stock', estimatedShipping: 'Sẵn hàng · Giao trong 3-5 ngày làm việc', batchLabel: 'Sẵn hàng', image: 'cap-physical', digitalImage: 'cap-digital', includes: ['1 nón cotton có khóa điều chỉnh', 'Không kèm nón avatar'] },
  { id: 'product-cap-digital', familyId: 'star-cap', title: 'Nón Everyday Star · Digital', priceVND: 30000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'cap-digital', digitalImage: 'cap-digital', digitalSlot: 'hat', digitalItemId: 'star-cap', includes: ['1 nón cho avatar VieWorld', 'Không có sản phẩm vật lý'] },
  { id: 'product-cd-real', familyId: 'first-notes', title: 'First Notes · CD Album', priceVND: 320000, category: 'album', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến phát hành: Tháng 11/2026', batchLabel: 'Pre-order', image: 'cd-physical', description: 'Album mẫu của Artist A. Minh họa bao bì; không chứa bản ghi thương mại hoặc quyền phát nhạc.', includes: ['1 CD và bìa giấy mẫu', 'Không kèm album số hoặc quyền streaming'] },
  { id: 'product-lightstick-real', familyId: 'star-light', title: 'Star Light · Lightstick', priceVND: 690000, category: 'merch', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 10/2026', batchLabel: 'Đợt 1', image: 'lightstick-physical', digitalImage: 'lightstick-digital', includes: ['1 lightstick và dây đeo mẫu', 'Không kèm phiên bản avatar'] },
  { id: 'product-lightstick-digital', familyId: 'star-light', title: 'Star Light · Digital', priceVND: 55000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'lightstick-digital', digitalImage: 'lightstick-digital', digitalSlot: 'lightstick', digitalItemId: 'star-light', includes: ['1 lightstick cầm tay cho avatar', 'Không phải quyền vào concert'] },
  { id: 'product-member-preview', familyId: 'club-pass', title: 'Artist A · Club Membership', priceVND: 0, category: 'membership', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt thẻ thành viên qua luồng riêng', batchLabel: 'Membership', image: 'membership-digital', previewOnly: true, includes: ['Thẻ hội viên digital minh họa', 'Xem và kích hoạt membership qua luồng mô phỏng riêng', 'Không kèm membership kit vật lý; không cam kết artist trả lời'] },
  { id: 'product-ticket-preview', familyId: 'live-pass', title: 'Live House · Concert Pass', priceVND: 0, category: 'ticket', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Vé sự kiện demo · Chưa mở bán', batchLabel: 'Event', image: 'ticket-digital', previewOnly: true, includes: ['Thiết kế vé digital mẫu · Chưa mở bán', 'Không có QR sử dụng được hoặc quyền vào cửa thật', 'Nhắc lịch RSVP không phải mua vé'] },

  // === ARTIST MIRA: SET 1 (Cloud Dream Hoodie & Duo) ===
  { id: 'product-mira-hoodie-real', familyId: 'mira-hoodie', worldId: 'artist-mira', title: 'Áo Hoodie MIRA Cloud Dream', priceVND: 520000, category: 'merch', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 11/2026', batchLabel: 'Đợt 1', image: 'mira-hoodie-physical', digitalImage: 'mira-hoodie-digital', description: 'Áo nỉ hoodie dáng suông màu tím khói pastel lavender, dệt từ sợi cotton mềm mại. Ngực trái thêu họa tiết mặt trăng bạc và mây phát sáng.', sizes: ['S', 'M', 'L', 'XL'], includes: ['1 áo hoodie cotton nỉ lavender ngoài đời', 'Không kèm trang phục avatar'] },
  { id: 'product-mira-hoodie-digital', familyId: 'mira-hoodie', worldId: 'artist-mira', title: 'Áo Hoodie MIRA Cloud Dream · Digital', priceVND: 49000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'mira-hoodie-digital', digitalImage: 'mira-hoodie-digital', digitalSlot: 'shirt', digitalItemId: 'mira-hoodie', includes: ['1 áo hoodie lavender cho avatar VieWorld', 'Không giao áo ngoài đời'] },
  { id: 'product-mira-hoodie-bundle', familyId: 'mira-hoodie', worldId: 'artist-mira', title: 'Áo Hoodie MIRA Cloud Dream · Duo Set', priceVND: 550000, category: 'merch', delivery: 'bundle', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 11/2026', batchLabel: 'Đợt 1', image: 'mira-hoodie-physical', digitalImage: 'mira-hoodie-digital', digitalSlot: 'shirt', digitalItemId: 'mira-hoodie', sizes: ['S', 'M', 'L', 'XL'], includes: ['1 áo hoodie ngoài đời thực', '1 trang phục avatar sau bàn giao mô phỏng'] },

  // === ARTIST MIRA: SET 2 (Crescent Lightstick & Vinyl Album) ===
  { id: 'product-mira-lightstick-real', familyId: 'mira-lightstick', worldId: 'artist-mira', title: 'Lightstick MIRA Crescent Glow', priceVND: 750000, category: 'merch', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 11/2026', batchLabel: 'Official Lightstick', image: 'mira-lightstick-physical', digitalImage: 'mira-lightstick-digital', description: 'Gậy phát sáng cổ vũ chính thức của MIRA. Cầu pha lê trong suốt ôm trọn vầng trăng khuyết phát ánh sáng tím lavender dịu dàng.', includes: ['1 lightstick MIRA Crescent Glow chính hãng', 'Dây đeo cổ tay và hộp trưng bày'] },
  { id: 'product-mira-lightstick-digital', familyId: 'mira-lightstick', worldId: 'artist-mira', title: 'Lightstick MIRA Crescent Glow · Digital', priceVND: 59000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'mira-lightstick-digital', digitalImage: 'mira-lightstick-digital', digitalSlot: 'lightstick', digitalItemId: 'mira-lightstick', includes: ['1 lightstick phát sáng tím cho avatar', 'Cầm trên tay khi tham dự Live Stage'] },
  { id: 'product-mira-vinyl-real', familyId: 'mira-vinyl', worldId: 'artist-mira', title: 'Đĩa than Vinyl MIRA "Midnight Reverie"', priceVND: 890000, category: 'album', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến phát hành: Tháng 12/2026', batchLabel: 'Limited Vinyl', image: 'mira-vinyl-physical', description: 'Phiên bản đĩa than màu tím hoa cà cẩm thạch giới hạn của album đầu tay "Midnight Reverie". Bìa gatefold cao cấp kèm sách ảnh nghệ thuật.', includes: ['1 đĩa than vinyl màu tím 12-inch 180g', 'Bìa gatefold mỹ thuật kèm photobook'] },

  // === ARTIST KAI: SET 3 (Cyber Pulse Bomber & Duo) ===
  { id: 'product-kai-bomber-real', familyId: 'kai-bomber', worldId: 'artist-kai', title: 'Áo khoác Bomber KAI Pulse Wave', priceVND: 680000, category: 'merch', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 11/2026', batchLabel: 'Streetwear Ed.', image: 'kai-bomber-physical', digitalImage: 'kai-bomber-digital', description: 'Áo khoác bomber phong cách đường phố tương lai, chất liệu technical fabric chống nước màu than chì với viền sọc cyber-teal neon phản quang.', sizes: ['M', 'L', 'XL', '2XL'], includes: ['1 áo khoác bomber phản quang ngoài đời', 'Không kèm trang phục avatar'] },
  { id: 'product-kai-bomber-digital', familyId: 'kai-bomber', worldId: 'artist-kai', title: 'Áo khoác Bomber KAI Pulse Wave · Digital', priceVND: 49000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'kai-bomber-digital', digitalImage: 'kai-bomber-digital', digitalSlot: 'shirt', digitalItemId: 'kai-bomber', includes: ['1 áo khoác bomber cyberpunk cho avatar', 'Tương thích mọi phòng trong VieWorld'] },
  { id: 'product-kai-bomber-bundle', familyId: 'kai-bomber', worldId: 'artist-kai', title: 'Áo khoác Bomber KAI Pulse Wave · Duo Set', priceVND: 710000, category: 'merch', delivery: 'bundle', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 11/2026', batchLabel: 'Duo Set', image: 'kai-bomber-physical', digitalImage: 'kai-bomber-digital', digitalSlot: 'shirt', digitalItemId: 'kai-bomber', sizes: ['M', 'L', 'XL', '2XL'], includes: ['1 áo khoác bomber ngoài đời', '1 trang phục avatar cyberpunk tương ứng'] },

  // === ARTIST KAI: SET 4 (Wave Lightstick & Cassette Tape Set) ===
  { id: 'product-kai-lightstick-real', familyId: 'kai-lightstick', worldId: 'artist-kai', title: 'Lightstick KAI Wave Shaker', priceVND: 720000, category: 'merch', delivery: 'physical', releaseType: 'pre_order', estimatedShipping: 'Dự kiến giao hàng: Tháng 11/2026', batchLabel: 'Official Lightstick', image: 'kai-lightstick-physical', digitalImage: 'kai-lightstick-digital', description: 'Gậy cổ vũ chính thức KAI Wave Shaker phong cách cyberpunk góc cạnh. Cụm đèn LED neon equalizer phát sáng nhấp nháy đồng bộ theo nhịp bass.', includes: ['1 lightstick KAI Wave Shaker đa chế độ đèn', 'Dây đeo tay dệt công nghệ cao'] },
  { id: 'product-kai-lightstick-digital', familyId: 'kai-lightstick', worldId: 'artist-kai', title: 'Lightstick KAI Wave Shaker · Digital', priceVND: 59000, category: 'merch', delivery: 'digital', releaseType: 'in_stock', estimatedShipping: 'Kích hoạt ngay vào My Space sau xác nhận', batchLabel: 'Digital', image: 'kai-lightstick-digital', digitalImage: 'kai-lightstick-digital', digitalSlot: 'lightstick', digitalItemId: 'kai-lightstick', includes: ['1 lightstick neon cyan cho avatar', 'Hiệu ứng ánh sáng rực rỡ tại concert'] },
  { id: 'product-kai-cassette-real', familyId: 'kai-cassette', worldId: 'artist-kai', title: 'Băng Cassette KAI "City Pulse Beats" Boxset', priceVND: 350000, category: 'album', delivery: 'physical', releaseType: 'in_stock', estimatedShipping: 'Sẵn hàng · Giao trong 3-5 ngày làm việc', batchLabel: 'Cassette Tape', image: 'kai-cassette-physical', description: 'Băng cassette vỏ nhựa trong suốt màu xanh neon cyan độc đáo chứa tuyển tập các bản synth-wave và future beats. Kèm hộp slipcase dập kim tuyến.', includes: ['1 băng cassette trong suốt màu cyan', 'Hộp đựng slipcase kèm bộ 5 sticker hologram KAI'] },
].map(p => [p.id, { ...base, ...p } as Product]));

/** Additive catalogue migration: preserve stock, orders, custom products and other tenants. */
export function withMerchCatalog(state: AppState): AppState {
  if (state.activeTenantId !== 'vieworld-demo' || !state.worlds['artist-a']) return state;
  const missing = Object.values(NEW_MERCH).filter(p => !state.products[p.id]);
  if (!missing.length) return state;
  return { ...state, products: { ...state.products, ...Object.fromEntries(missing.map(p => [p.id, { ...p }])) } };
}

export function ownsDigitalProduct(state: AppState, product: Product) {
  return !!product.digitalItemId && Object.values(state.orders).some(o => o.fanId === state.fanProfile.id && o.status === 'fulfilled' && state.products[o.productId]?.digitalItemId === product.digitalItemId);
}

export function canEnterHall(state: AppState, worldId: string) {
  return Object.values(state.memberships).some(m => m.worldId === worldId && m.fanId === state.fanProfile.id && m.status === 'active' && (!m.expiresAt || Date.parse(m.expiresAt) > Date.parse(state.demoTime)));
}

/** Never render a revoked item simply because an old appearance was saved. */
export function ownedDigitalLook(state: AppState) {
  const look: NonNullable<AppState['fanProfile']['digitalLook']> = {};
  for (const slot of ['shirt', 'hat', 'lightstick'] as const) {
    const item = state.fanProfile.digitalLook?.[slot];
    if (item && Object.values(state.products).some(p => p.digitalSlot === slot && p.digitalItemId === item && ownsDigitalProduct(state,p))) look[slot] = item;
  }
  return look;
}
